import { Button, Checkbox, Form, Image, Input, message, notification, Spin } from "antd";
import React, { useContext, useEffect, useRef, useState } from "react";
import BaseLayout from "../../components/Layout/BaseLayout"; import css from "./style.module.css";
import { UserOutlined, LockOutlined } from "@ant-design/icons";
import { useTranslation } from "next-i18next";
import axios from "axios";
import { useRouter } from "next/router";
import BasketContext from "../../context/basketContext/BasketContext";
import sha256 from "sha256";
import Head from "next/head";
import ForgetPassword from "../../components/ForgetPassword";
import ReCAPTCHA from "react-google-recaptcha";
export default function Login() {
  const router = useRouter();
  const { t } = useTranslation("login");
  const [username, setUsername] = useState();
  const [password, setPassword] = useState();
  const basketContext = useContext(BasketContext);
  const [toggle, setToggle] = useState(1); 
  const [btnDis, setBtnDis]= useState(true);
  const [spinCapt, setSpinCapt] = useState(0);
  const recaptchaRef = useRef();
  useEffect(()=>{
    setTimeout(()=>{
      console.log("spin");
      setSpinCapt(1);
    },800)
  },[])
  const onFinish = (values) => { 
    var passwordHash = sha256(password); 
    const body = {func: "signIn",username: username,password: passwordHash,};  
    axios.post("/api/post/Gate", body).then((res) => {
        if (res.data.data.username) {
          message.success(t("Success"));
          localStorage.setItem("pkId", res.data.data.pkId);
          localStorage.setItem("token", res.data.data.token);
          // localStorage.setItem("username", res.data.data.username);
          // localStorage.setItem("lastname", res.data.data.lastname);
          // localStorage.setItem("phone", res.data.phone);
          // localStorage.setItem("firstname", res.data.data.firstname);
          localStorage.setItem("state", res.data.data.state);
          // localStorage.setItem("isSuperAdmin", res.data.data.isSuperAdmin);
          basketContext.getUserProfileFunction();
          router.push("/");
        } else {
          recaptchaRef.current.props.grecaptcha.reset();
          notification["error"]({ message: 'Submit Error',description:'These credentials do not match our records.'}); 
          setBtnDis(true);
        }
      }).catch((err) => {console.log("Username and password are incorrect!!")}); 
  };
  const onFinishFailed = (errorInfo) => {
    // console.log("Failed:", errorInfo);
  };
  const registerBtn = () => {
    router.push("register");
  };
  const forgotPassword = (a) => {
    if (a === "1") {
      setToggle(1);
    } else {
      setToggle(0);
    }
  };
  const onChangeCaptcha = (a) =>{ 
    console.log("captcha change: ", a);
    a == null ? setBtnDis(true) : setBtnDis(false)
  }
  const errorCapt = (err) =>{
    console.log("err", err);
  }
  const loadFun = (a) =>{
    console.log("load: ", a);
  }
  return (
    <div> <Head><title>OBORTECH</title><meta name="description" content="Generated by create next app" /> <link rel="icon" href="img/HeaderLogo.png" /></Head>
      <BaseLayout pageName="login">
        <div className={css.Cont}  >
          <div className={css.Cont2}>
            <div className={css.LoginTitle}> <Image alt="Obertech" preview={false} src="/img/HeaderLogo.png" width={80}  style={{borderRadius: "5px"}}/></div>
            <div className={css.HdrTitle}>
              <div>Sign in to your account</div>
              <div className={css.OrCss}>Or <Button className={css.RegisterHover} onClick={registerBtn}type="link">{t("Create An Account")}</Button></div>
            </div>
            <div className={css.FromCss}>
              {toggle === 1 ? (
                <Form name="normal_login" className={css.LoginForm} initialValues={{ remember: true, }} onFinish={onFinish} onFinishFailed={onFinishFailed}>
                  <Form.Item name="username" rules={[{ required: true, message: t("Please input your Username!")}]}>
                    <Input size="large" onChange={(e) => setUsername(e.target.value)} prefix={<UserOutlined className={css.IconCss} />} placeholder={t("User name")}/>
                    </Form.Item>
                  <Form.Item name="password" rules={[ { required: true, message: t("Please input your Password!")}]}>
                    <Input.Password size="large" onChange={(e) => setPassword(e.target.value)} prefix={<LockOutlined className={css.IconCss} />} type="password" placeholder={t("password")}/>
                  </Form.Item>
                  <Form.Item>
                    <Form.Item name="remember" valuePropName="checked" noStyle><Checkbox>{t("Remember me")}</Checkbox></Form.Item>
                    <a className={css.Forget} onClick={forgotPassword}>{t("Forgot password")}</a>
                  </Form.Item>
                   {/* obortech: 6Ld-prciAAAAAOY-Md7hnxjnk4hD5wbh8bK4ld5t ============================================================*/} 
                  {/* my ip:  6LfnfrUiAAAAAJ-K132PVlBOqV-fr1F1sBOJcGpR ===============================================================*/}
                  <div className={css.CaptchaCss}> {spinCapt  == 0 ? <Spin /> : <ReCAPTCHA   onErrored={errorCapt}  ref={recaptchaRef} sitekey="6Ld-prciAAAAAOY-Md7hnxjnk4hD5wbh8bK4ld5t" onChange={onChangeCaptcha}/> }</div>
                 
                  <Form.Item>
                    <div className={css.Login}>
                      <Button size="large" disabled={btnDis} type="primary" htmlType="submit" className="login-form-button">{t("Log in")}</Button>
                      {/* <div className={css.OrRegister}>{t("New here")}?<Button className={css.RegisterHover} onClick={registerBtn}type="link">{t("Create An Account")}</Button></div> */}
                    </div>
                  </Form.Item>
                </Form>
              ) : (<div className={css.ForgetPasswordCss}><ForgetPassword forgotPassword={forgotPassword} /></div>)}
            </div>
          </div>
        </div>
      </BaseLayout>
    </div>
  );
}
